services:
  app:
    build:
      context: .
      dockerfile: dockerfile

    ports: 
      - "3000:3000"
    depends_on:
      - db

    environment: 
      - DB_URI=mongodb://db:27017/mydatabase

    volumes:
      - .:/app
      - /app/node_modules

    command: yarn dev
    

  db:
    image: mongo

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db
    
volumes:
  mongo_data: