services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      target: dev

    env_file:
      - path: ./.env

    ports: 
      - "3000:3000"
      
    depends_on:
      - db

    environment: 
      DOCKER_DB_URI: ${DOCKER_DB_URI}

    volumes:
      - .:/app
      - /app/node_modules

    # command: yarn dev
    

  db:
    image: mongo

    ports:
      - "27017:27017"

    env_file:
      - path: ./.env

    environment:
        MONGO_INITDB_ROOT_USERNAME: ${ADMIN_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${ADMIN_PASSWORD}

    volumes:
      - mongo_data:/data/db
    

  mongo_express:
    image: mongo-express
  
    ports:
      - "8081:8081"

    depends_on:
      - db
    
    env_file:
      - path: ./.env
    
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${ADMIN_USERNAME}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${ADMIN_PASSWORD}
        ME_CONFIG_MONGODB_SERVER: db
        ME_CONFIG_MONGODB_URL: ${DOCKER_DB_URI}
        ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
        ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

    
volumes:
  mongo_data: